//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEdit {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEdit.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буфер обмена.
        /// </summary>
        internal static string ClipboardLab {
            get {
                return ResourceManager.GetString("ClipboardLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение для сохранения.
        /// </summary>
        internal static string ClipboardPlace {
            get {
                return ResourceManager.GetString("ClipboardPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clipboard.
        /// </summary>
        internal static string ClipboardTitle {
            get {
                return ResourceManager.GetString("ClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ-значение (через #).
        /// </summary>
        internal static string DictPlace {
            get {
                return ResourceManager.GetString("DictPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Второй набор.
        /// </summary>
        internal static string Extended {
            get {
                return ResourceManager.GetString("Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить доступ.
        /// </summary>
        internal static string GetNetwork {
            get {
                return ResourceManager.GetString("GetNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить профили сети.
        /// </summary>
        internal static string GetProfile {
            get {
                return ResourceManager.GetString("GetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите URI:.
        /// </summary>
        internal static string HomeSearchBar {
            get {
                return ResourceManager.GetString("HomeSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невалидный URI!.
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ к сети Интернет.
        /// </summary>
        internal static string NetActive {
            get {
                return ResourceManager.GetString("NetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограниченный доступ к сети.
        /// </summary>
        internal static string NetConstrained {
            get {
                return ResourceManager.GetString("NetConstrained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние сети.
        /// </summary>
        internal static string NetLab {
            get {
                return ResourceManager.GetString("NetLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы в локальной сети.
        /// </summary>
        internal static string NetLocal {
            get {
                return ResourceManager.GetString("NetLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без доступа к сети.
        /// </summary>
        internal static string NetNone {
            get {
                return ResourceManager.GetString("NetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УВЕДОМЛЯТЬ ОБ ИЗМЕНЕНИИ.
        /// </summary>
        internal static string NetNotify {
            get {
                return ResourceManager.GetString("NetNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус сети изменен!.
        /// </summary>
        internal static string NetStatus {
            get {
                return ResourceManager.GetString("NetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Net.
        /// </summary>
        internal static string NetTitle {
            get {
                return ResourceManager.GetString("NetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение не найдено!.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ок.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кэш OS.
        /// </summary>
        internal static string PreferencesLabel {
            get {
                return ResourceManager.GetString("PreferencesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preferences.
        /// </summary>
        internal static string PrefTitle {
            get {
                return ResourceManager.GetString("PrefTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безопасное хранилище                                                                                                                          (Хранилище ключей Android).
        /// </summary>
        internal static string SecureLab {
            get {
                return ResourceManager.GetString("SecureLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SecureStorage.
        /// </summary>
        internal static string SecureTitle {
            get {
                return ResourceManager.GetString("SecureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый набор.
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОЗВУЧИТЬ.
        /// </summary>
        internal static string TTSButton {
            get {
                return ResourceManager.GetString("TTSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;h1&gt;Доступные локали:&lt;/h1&gt;.
        /// </summary>
        internal static string TTSHeader {
            get {
                return ResourceManager.GetString("TTSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст в речь.
        /// </summary>
        internal static string TTSLabel {
            get {
                return ResourceManager.GetString("TTSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тон:.
        /// </summary>
        internal static string TTSPitch {
            get {
                return ResourceManager.GetString("TTSPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст для озвучки.
        /// </summary>
        internal static string TTSPlace {
            get {
                return ResourceManager.GetString("TTSPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextToSpeech.
        /// </summary>
        internal static string TTSTitle {
            get {
                return ResourceManager.GetString("TTSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Громкость:.
        /// </summary>
        internal static string TTSVolume {
            get {
                return ResourceManager.GetString("TTSVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВВЕРХ.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
    }
}
